module.exports = {
    'SMS_EXPIRATION_MSG' : ': OTP is valid for 30 minutes- Suzuki 2W',
    'SMS_SENT_ERR' : 'Unable to send OTP',
    'OPERATION_FAILURE_ERR' : 'Unable to process your request at this moment. Please contact at  customer.queries@suzukimotorcycle.in and share details with your mobile no.',
    'INVALID_DATA_ERR' : 'Invalid data',
    'NO_DATA_FOUND_ERR' : 'No data found',
    'USER_ALREADY_EXISTS_ERR' : 'User already exist',
    'USER_NOT_FOUND_ERR' : 'User does not exist',
    'VIN_REQUIRED_ERR' : 'VIN number required',
    'DEALER_CODE_REQUIRED_ERR' : 'Dealer Code number required',
    'STATE_CODE_REQUIRED_ERR' : 'State Code required',
    'APP_NUMBER_REQUIRED_ERR' : 'Appointment number required',
    'NO_BOOKING_FOUND' : 'No booking found',
    'BOOKING_SLOT_REQUIRED_ERR' : 'Booking Slot required',
    'OTP_EXPIRED' : 'Your OTP has been expired. Please click on resend link to generate new OTP.',
    SERVICE_BOOKING_MESSAGE: 'Your Service Booking request has been submitted successfully. Appointment code is ',
    MORE_SERVICE_HISTORY_DETAILS : '. Go to Service History for more details.',
    NO_DEALER_FOUND : 'No dealer found',
    INCORRECT_OTP : 'Incorrect OTP',
    ODOMETER_READING_ERR : 'Please enter Odometer reading greater than previous one Odometer reading. Please refer Service History for more details',
    RATING_ERR : 'Please provide rating',
    PENDING_SH_RATING : {'errCode' : 'SZ_BS_001', 'msg' : 'Please provide the feedback for past services'},
    CANCEL_PRE_BOOKING : {'errCode' : 'SZ_BS_001', 'msg' : 'Please cancel previous booked services'},
    VIN_EXIST_ERR : 'VIN already exists',
    VIN_NOT_FOUND_ERR : 'VIN not found for your registered mobile. Please contact to your nearest dealer',
    TOKEN_EXIST_ERR : 'Device token already exists',
    CITY_CODE_REQUIRED_ERR : 'City Code required',
    NOT_ELIGIBLE_FOR_SERVICE_ERR : 'You are not eligible for Free Service. Please select Paid or Unscheduled Service for any booking.',
    NO_EMPLOYEE_FOUND : 'No employee found',
    MISMATCH_MOBILE_NO: 'Your mobile number does not exists. Please contact to your nearest Dealer.'
};